# Generated by Django 6.1 on 2026-09-17 09:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_parking_locations(apps, schema_editor):
    ParkingLocation = apps.get_model("parking", "ParkingLocation")
    ParkingSpot = apps.get_model("parking", "ParkingSpot")
    locations = [
        ("Asia Mall", "пр. Чингиза Айтматова, 3", 42.858800, 74.559000, 12),
        ("Bishkek Park", "ул. Киевская, 148", 42.874700, 74.594000, 10),
        ("Dordoi Plaza", "ул. Ибраимова, 115", 42.879300, 74.612000, 14),
        ("Vefa", "ул. Горького, 27/1", 42.847700, 74.616000, 8),
    ]
    for name, address, latitude, longitude, total_spots in locations:
        location = ParkingLocation.objects.create(
            name=name,
            address=address,
            latitude=latitude,
            longitude=longitude,
            total_spots=total_spots,
        )
        ParkingSpot.objects.bulk_create([
            ParkingSpot(location=location, number=number)
            for number in range(1, total_spots + 1)
        ])


def remove_seed_parking_locations(apps, schema_editor):
    ParkingLocation = apps.get_model("parking", "ParkingLocation")
    ParkingLocation.objects.filter(name__in=["Asia Mall", "Bishkek Park", "Dordoi Plaza", "Vefa"]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('total_spots', models.PositiveIntegerField(default=0, verbose_name='Всего мест')),
            ],
            options={
                'verbose_name': 'парковка',
                'verbose_name_plural': 'парковки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер места')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занято')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkinglocation', verbose_name='парковка')),
            ],
            options={
                'verbose_name': 'парковочное место',
                'verbose_name_plural': 'парковочные места',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingspot', verbose_name='место')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('location', 'number'), name='unique_spot_per_location'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.RunPython(seed_parking_locations, remove_seed_parking_locations),
    ]
