# Generated by Django 6.1.1 on 2026-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Цена за час'),
        ),
    ]
