# Generated by Django 6.1.1 on 2026-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking_amount_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['spot', 'is_active', 'end_time'], name='booking_spot_active_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'is_active', 'start_time'], name='booking_user_active_idx'),
        ),
    ]
